### ISSUE TITLE
Double images

### ISSUE THREAD

**Issue by DutchPete** [kinmury/Golden-Book#12]
I have 2 plug-ins: *CodeMirror Options* and *Ozan's Image in Editor*. If I have the option to render images in Edit mode in both plug-ins, I get each image shown 2x in Golden Book, whereas in e.g. ITS the same settings enabled simultaneously only renders the image once.

In fact, I was not aware this occurred until I started using both plug-ins in GB.

Please note: it makes more sense to have that specific setting disabled in one of the plug-ins. I am reporting the issue of 2 images in Golden Book in case there is something technically not quite right in GB. As far as I am concerned you don't have to fix it. 😀

**Comment by kinmury** [comment]
Since this Issue is not related too much to the theme (and I actually don't know what to do about it, I'll close it)
