### ISSUE TITLE
[Feature Request] Aside notes

### ISSUE THREAD

**Issue by DutchPete** [kinmury/Golden-Book#4]
There are 3 different types of aside notes as per the ITS theme. I would like to be able to use aside-hide.

**Comment by kinmury** [comment]
I have a thing to say about the `ASIDE NOTES`. I removed them from the theme. If you want to use them, you should download the `Aside_Notes` snippet. 

Sorry for the inconvenience.

**Comment by DutchPete** [comment]
That is an acceptable alternative. 😀
