### ISSUE TITLE
Pop-up text overflows

### ISSUE THREAD

**Issue by DutchPete** [kinmury/Golden-Book#6]
See screenshot.

![image](https://user-images.githubusercontent.com/10794265/139381541-727425c1-f2d8-4b06-91d9-3930f7193f0c.png)

**Comment by DutchPete** [comment]
Yes, it is fixed. The only thing is that the full link text is now on a 1-line popup. Esthetically it would be nicer to have the text wrap, like it was with some links before: they were long but fitted wrapped in a shorter popup.

It is not a big deal to leave it as it is now.

**Comment by kinmury** [comment]
It is done. I uploaded it on the CSS, not the release. I'll make another release once the Embeded  Video Issue is fixed. 

Thank you for your contribution, I really appreciate it :D

**Comment by DutchPete** [comment]
Fantastic ! Well done ! 👍
